import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "local-video-1",
    video_title: "Website Showcase",
    video_description: `Sleek presentation of Website interface with gesture-based interactions and animations.`,
    tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "/Saas/thumbnails/1.png",
    publish_date: "2024-08-04",
    client_name: "Creative Script",
    client_image: "/Saas/cs.png",
    client_feedback: "The website showcase exceeded our expectations. The smooth animations and interactive elements perfectly captured our brand's modern aesthetic.",
    video_link: "/Saas/with_sound.mp4",
    video_type: "local",
    project_images: [],
    category: ["Motion Graphics", "Web Animation"],
    duration: "6:32",
    software_used: ["After Effects", "Premiere Pro"],
  },
  {
    id: "local-video-2",
    video_title: "Sales Dashboard Promo",
    video_description:
      "product demo showcasing key analytics features and user workflow automation.",
    tags: ["DSA", "Developer Skills", "Problem Solving", "Career Prep"],
    cover_image: "/Saas/thumbnails/2.png",
    publish_date: "2024-04-08",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "Outstanding dashboard promo that clearly communicates our platform's value proposition. The workflow visualization is spot-on.",
    video_link: "/Saas/with_audio.mp4",
    video_type: "local",
    project_images: [],
    category: ["Motion Graphics", "Web Animation"],
    duration: "10:12",
    software_used: ["After Effects", "Premiere Pro"],
  },
  {
    id: "local-video-3",
    video_title: "Website Intro",
    video_description: `Comprehensive brand identity animation featuring logo reveals, color schemes, and brand elements with modern motion design principles`,
    tags: ["Web Animation", "UI/UX", "Motion Graphics", "Landing Page"],
    cover_image: "/Saas/thumbnails/9.png",
    publish_date: "2024-08-05",
    client_name: "Creative Agency",
    client_image: "/Saas/cs.png",
    client_feedback: "The website intro animation perfectly captures our brand essence. The smooth transitions and engaging visuals really impressed our clients.",
    video_link: "/Saas/glass.mp4",
    video_type: "local",
    project_images: ["/Saas/thumbnails/3.png", "/Saas/thumbnails/4.png"],
    category: ["Motion Graphics", "Web Animation"],
    duration: "2:15",
    software_used: ["After Effects", "Premiere Pro"],
  },
  {
    id: "local-video-4",
    video_title: "Landing Page Animation",
    video_description: `Dynamic landing page animation showcasing modern web design principles with smooth transitions and engaging visual effects.`,
    tags: ["Web Animation", "UI/UX", "Motion Graphics", "Landing Page"],
    cover_image: "/Saas/thumbnails/3.png",
    publish_date: "2024-08-05",
    client_name: "Creative Agency",
    client_image: "/Saas/cs.png",
    client_feedback: "The landing page animation is exactly what we needed. It creates an engaging user experience that keeps visitors on our site longer.",
    video_link: "/Saas/landpill.mp4",
    video_type: "local",
    project_images: ["/Saas/thumbnails/3.png", "/Saas/thumbnails/4.png"],
    category: ["Motion Graphics", "Web Animation"],
    duration: "2:15",
    software_used: ["After Effects", "Premiere Pro"],
  },
  {
    id: "local-video-5",
    video_title: "The Rise,Fall and Legacy of Napoleon Bonaparte",
    video_description: `Explore the fascinating journey of Napoleon Bonaparte, one of history's most influential leaders.`,
    tags: ["Brand Identity", "Logo Animation", "Motion Graphics", "Branding"],
    cover_image: "/Saas/thumbnails/Napolean.png",
    publish_date: "2024-08-07",
    client_name: "Elton",
    client_image: "/Saas/client.png",
    client_feedback: "This historical video is a masterpiece. The storytelling and visual effects bring Napoleon's story to life in a way that's both educational and entertaining.",
    video_link: "/Saas/video2.mp4",
    video_type: "local",
    project_images: ["/Saas/thumbnails/7.png", "/Saas/thumbnails/8.png"],
    category: ["Documentary"],
    duration: "1:52",
    software_used: ["After Effects", "Premiere Pro"],
  },
  {
    id: "local-video-6",
    video_title: "THE GREAT FLOOD: THE UNTOLD STORY OF NOAH'S ARK",
    video_description: `Explore the fascinating journey of Napoleon Bonaparte, one of history's most influential leaders.`,
    tags: ["Brand Identity", "Logo Animation", "Motion Graphics", "Branding"],
    cover_image: "/Saas/thumbnails/Noah.png",
    publish_date: "2024-08-07",
    client_name: "Elton",
    client_image: "/Saas/client.png",
    client_feedback: "The Noah's Ark story is beautifully told through stunning visuals and compelling narration. This video has become a cornerstone of our educational content.",
    video_link: "/Saas/lt_video2.mp4",
    video_type: "local",
    project_images: ["/Saas/thumbnails/7.png", "/Saas/thumbnails/8.png"],
    category: ["Documentary"],
    duration: "1:52",
    software_used: ["After Effects", "Premiere Pro"],
  },
  {
    id: "local-video-7",
    video_title: "Product Showcase Video",
    video_description: `Professional product showcase highlighting key features and benefits with compelling visual storytelling and smooth motion graphics.`,
    tags: ["Product Video", "Showcase", "Motion Graphics", "Marketing"],
    cover_image: "/Saas/thumbnails/5.png",
    publish_date: "2024-08-06",
    client_name: "Tech Solutions",
    client_image: "/Saas/client.png",
    client_feedback: "The product showcase video perfectly highlights our key features. The visual storytelling makes complex technology easy to understand for our customers.",
    video_link: "/Saas/lt_video4.mp4",
    video_type: "local",
    project_images: ["/Saas/thumbnails/5.png", "/Saas/thumbnails/6.png"],
    category: ["Motion Graphics", "Promo"],
    duration: "3:45",
    software_used: ["After Effects", "Davinci Resolve"],
  },
  {
    id: "local-video-8",
    video_title: "Brand Identity Animation",
    video_description: `Comprehensive brand identity animation featuring logo reveals, color schemes, and brand elements with modern motion design principles.`,
    tags: ["Brand Identity", "Logo Animation", "Motion Graphics", "Branding"],
    cover_image: "/Saas/thumbnails/7.png",
    publish_date: "2024-08-07",
    client_name: "Brand Studio",
    client_image: "/Saas/client.png",
    client_feedback: "The brand identity animation perfectly represents our company's vision and values. It's become an essential part of our brand presentation.",
    video_link: "/Saas/5th.mp4",
    video_type: "local",
    project_images: ["/Saas/thumbnails/7.png", "/Saas/thumbnails/8.png"],
    category: ["Motion Graphics","Web Animation"],
    duration: "1:52",
    software_used: ["After Effects", "Premiere Pro"],
  },
  {
    id: "local-video-9",
    video_title: "AI labs promo video",
    video_description: `From smart algorithms to real-world AI solutions, we're turning ideas into innovation. Join us and experience the power of AI shaping tomorrow`,
    tags: ["Brand Identity", "Logo Animation", "Motion Graphics", "Branding"],
    cover_image: "/Saas/thumbnails/AI_LABS.png",
    publish_date: "2024-08-07",
    client_name: "Creative Script",
    client_image: "/Saas/cs.png",
    client_feedback: "The AI labs promo perfectly captures the cutting-edge nature of our work. The futuristic visuals and messaging align perfectly with our brand.",
    video_link: "/Saas/AI_labs.mp4",
    video_type: "local",
    project_images: ["/Saas/thumbnails/7.png", "/Saas/thumbnails/8.png"],
    category: ["Promo"],
    duration: "1:52",
    software_used: ["After Effects", "Premiere Pro"],
  },
  {
    id: "local-video-10",
    video_title: "Dodo Payments Beta version launch video",
    video_description: `From smart algorithms to real-world AI solutions, we're turning ideas into innovation. Join us and experience the power of AI shaping tomorrow`,
    tags: ["Brand Identity", "Logo Animation", "Motion Graphics", "Branding"],
    cover_image: "/Saas/thumbnails/6.png",
    publish_date: "2024-08-07",
    client_name: "Dodo Payments",
    client_image: "/Saas/dp.png",
    client_feedback: "The beta launch video exceeded our expectations. It effectively communicates our payment solution's benefits and has helped drive user adoption.",
    video_link: "/Saas/lt_video7.mp4",
    video_type: "local",
    project_images: ["/Saas/thumbnails/7.png", "/Saas/thumbnails/8.png"],
    category: ["Promo"],
    duration: "1:52",
    software_used: ["After Effects", "Premiere Pro"],
  },
  {
    id: "local-video-11",
    video_title: "Konster launch video",
    video_description: `Konster is your bridge between customers and constructors! This video highlights how the Konster app makes finding trusted construction services easy and efficient.`,
    tags: ["Brand Identity", "Logo Animation", "Motion Graphics", "Branding"],
    cover_image: "/Saas/thumbnails/4.png",
    publish_date: "2024-08-07",
    client_name: "Creative Script",
    client_image: "/Saas/cs.png",
    client_feedback: "The Konster launch video perfectly explains our platform's value proposition. The clear messaging and engaging visuals have helped us attract both customers and contractors.",
    video_link: "/Saas/Konster.mp4",
    video_type: "local",
    project_images: ["/Saas/thumbnails/7.png", "/Saas/thumbnails/8.png"],
    category: ["Motion Graphics", "app animation"],
    duration: "1:52",
    software_used: ["After Effects", "Premiere Pro"],
  },
  {
    id: "local-video-12",
    video_title: "Rapido Hook video",
    video_description: `Need to zip through traffic in minutes? 🚀 Rapido gets you moving fast, easy, and safe! Your ride, your way—anytime, anywhere.`,
    tags: ["Brand Identity", "Logo Animation", "Motion Graphics", "Branding"],
    cover_image: "/Saas/thumbnails/Rapido.png",
    publish_date: "2024-08-07",
    client_name: "Client",
    client_image: "/Saas/client.png",
    client_feedback: "The Rapido hook video is incredibly effective at capturing attention. The fast-paced editing and compelling messaging perfectly represent our ride-sharing service.",
    video_link: "/Saas/lt_video3.mp4",
    video_type: "local",
    project_images: ["/Saas/thumbnails/7.png", "/Saas/thumbnails/8.png"],
    category: ["Motion Graphics"],
    duration: "1:52",
    software_used: ["After Effects", "Premiere Pro"],
  },
  {
    id: "local-video-13",
    video_title: "Social Media Short Form Masterpiece",
    video_description: `Revolutionary short-form content designed for maximum engagement across all social media platforms with cutting-edge visual effects and compelling storytelling.`,
    tags: ["Short Form", "Social Media", "Visual Effects", "Engagement"],
    cover_image: "/Saas/thumbnails/st_1.png",
    publish_date: "2024-08-07",
    client_name: "Dodo Payments",
    client_image: "/Saas/dp.png",
    client_feedback: "This short-form video is a game-changer for our social media strategy. The engagement rates have increased dramatically since we started using it.",
    video_link: "/Saas/st_1.mp4",
    video_type: "local",
    project_images: ["/Saas/thumbnails/7.png", "/Saas/thumbnails/8.png"],
    category: ["Short form"],
    duration: "1:52",
    software_used: ["After Effects", "Premiere Pro"],
  },
  {
    id: "local-video-14",
    video_title: "Short Form Video 2",
    video_description: `Engaging short-form content designed for social media platforms with quick visual impact and compelling storytelling.`,
    tags: ["Short Form", "Social Media", "Motion Graphics", "Digital Marketing"],
    cover_image: "/Saas/thumbnails/st_2.png",
    publish_date: "2024-08-08",
    client_name: "Creative Agency",
    client_image: "/Saas/cs.png",
    client_feedback: "Perfect short-form content that captures attention immediately. Great for our social media strategy.",
    video_link: "/Saas/st_2.mp4",
    video_type: "local",
    project_images: ["/Saas/thumbnails/st_2.png"],
    category: ["Short form"],
    duration: "0:45",
    software_used: ["After Effects", "Premiere Pro"],
  },
  {
    id: "local-video-15",
    video_title: "Short Form Video 3",
    video_description: `Dynamic short-form animation optimized for mobile viewing with engaging visual elements and smooth transitions.`,
    tags: ["Short Form", "Mobile First", "Animation", "Social Media"],
    cover_image: "/Saas/thumbnails/st_3.png",
    publish_date: "2024-08-09",
    client_name: "Tech Solutions",
    client_image: "/Saas/client.png",
    client_feedback: "Excellent mobile-optimized content that performs well across all social platforms.",
    video_link: "/Saas/st_3.mp4",
    video_type: "local",
    project_images: ["/Saas/thumbnails/st_3.png"],
    category: ["Short form"],
    duration: "0:52",
    software_used: ["After Effects", "Davinci Resolve"],
  },
  {
    id: "local-video-16",
    video_title: "Short Form Video 4",
    video_description: `Creative short-form video with modern design aesthetics and engaging motion graphics for brand awareness.`,
    tags: ["Short Form", "Brand Awareness", "Motion Graphics", "Modern Design"],
    cover_image: "/Saas/thumbnails/st_4.png",
    publish_date: "2024-08-10",
    client_name: "Brand Studio",
    client_image: "/Saas/client.png",
    client_feedback: "Modern and engaging content that perfectly represents our brand identity.",
    video_link: "/Saas/st_4.mp4",
    video_type: "local",
    project_images: ["/Saas/thumbnails/st_4.png"],
    category: ["Short form"],
    duration: "0:48",
    software_used: ["After Effects", "Premiere Pro"],
  },
  {
    id: "local-video-17",
    video_title: "Short Form Video 5",
    video_description: `High-impact short-form content featuring dynamic animations and compelling visual storytelling for maximum engagement.`,
    tags: ["Short Form", "High Impact", "Animation", "Engagement"],
    cover_image: "/Saas/thumbnails/st_5.png",
    publish_date: "2024-08-11",
    client_name: "Creative Script",
    client_image: "/Saas/cs.png",
    client_feedback: "High-impact content that drives engagement and captures our audience's attention effectively.",
    video_link: "/Saas/st_5.mp4",
    video_type: "local",
    project_images: ["/Saas/thumbnails/st_5.png"],
    category: ["Short form"],
    duration: "0:55",
    software_used: ["After Effects", "Premiere Pro"],
  },
  {
    id: "local-video-18",
    video_title: "Short Form Video 6",
    video_description: `Innovative short-form video with cutting-edge visual effects and modern motion design principles.`,
    tags: ["Short Form", "Innovation", "Visual Effects", "Modern Design"],
    cover_image: "/Saas/thumbnails/st_6.png",
    publish_date: "2024-08-12",
    client_name: "Innovation Labs",
    client_image: "/Saas/client.png",
    client_feedback: "Innovative approach that sets us apart from competitors. The visual effects are outstanding.",
    video_link: "/Saas/st_6.mp4",
    video_type: "local",
    project_images: ["/Saas/thumbnails/st_6.png"],
    category: ["Short form"],
    duration: "0:50",
    software_used: ["After Effects", "Davinci Resolve"],
  },
  {
    id: "local-video-19",
    video_title: "Short Form Video 8",
    video_description: `Creative short-form masterpiece combining artistic vision with technical excellence for maximum visual impact.`,
    tags: ["Short Form", "Artistic", "Technical Excellence", "Visual Impact"],
    cover_image: "/Saas/thumbnails/st_8.png",
    publish_date: "2024-08-14",
    client_name: "Art Studio",
    client_image: "/Saas/cs.png",
    client_feedback: "A true masterpiece that combines artistic vision with technical excellence. Simply outstanding.",
    video_link: "/Saas/st_8.mp4",
    video_type: "local",
    project_images: ["/Saas/thumbnails/st_8.png"],
    category: ["Short form"],
    duration: "0:53",
    software_used: ["After Effects", "Davinci Resolve"],
  },
];
